# Generated by Django 5.2.6 on 2025-10-27 06:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_project_budget_alloue_project_statut"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="salaire_mensuel_base",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Salaire Mensuel de Base",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="statut_actuel",
            field=models.CharField(
                choices=[
                    ("ACTIF", "Actif"),
                    ("EN_CONGE", "En congé"),
                    ("INACTIF", "Inactif"),
                ],
                default="ACTIF",
                max_length=20,
                verbose_name="Statut actuel",
            ),
        ),
        migrations.CreateModel(
            name="Assignation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_debut_assignation",
                    models.DateField(verbose_name="Date de début d'assignation"),
                ),
                (
                    "date_fin_assignation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin d'assignation"
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignations_projet",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignations_employe",
                        to="projects.project",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignation Projet",
                "verbose_name_plural": "Assignations Projet",
                "unique_together": {("employe", "projet", "date_debut_assignation")},
            },
        ),
    ]
