# Generated by Django 5.2.6 on 2025-11-17 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Type de Contrat"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du Département"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IDType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Type de Pièce d'Identité",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True, verbose_name="Adresse"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="allergies",
            field=models.TextField(blank=True, verbose_name="Allergies"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="assigned_countries",
            field=models.ManyToManyField(
                blank=True, to="users.country", verbose_name="Pays d'affectation"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bank_account_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Numéro de compte bancaire"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="birth_country",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Pays de naissance"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=3,
                verbose_name="Groupe Sanguin",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="employee_id",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Numéro Matricule",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="eritop_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ID ERITOP"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="hire_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date d'embauche"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="id_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Numéro de la pièce d'identité"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="isignum_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Numéro ISIGNUM"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="job_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.role",
                verbose_name="Rôle",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nationalité"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="other_first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Autres prénoms"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="professional_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Adresse email professionnelle"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pics/",
                verbose_name="Photo de profil",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="recurring_illness",
            field=models.TextField(blank=True, verbose_name="Maladie récurrente"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="social_security_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Numéro de sécurité sociale"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="special_allergies",
            field=models.TextField(blank=True, verbose_name="Allergie particulière"),
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la Banque"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.country",
                        verbose_name="Pays",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "country")},
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.bank",
                verbose_name="Banque",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="contract_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.contracttype",
                verbose_name="Type de Contrat",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.department",
                verbose_name="Département",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(max_length=100, verbose_name="Type de document"),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to="employee_documents/", verbose_name="Document"
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="id_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.idtype",
                verbose_name="Type de pièce d'identité",
            ),
        ),
        migrations.CreateModel(
            name="ProfileUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_update",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
