# Generated by Django 5.2.6 on 2025-12-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_profileupdate_employee_profileupdatehistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileupdate",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
