# Generated by Django 5.2.6 on 2025-09-26 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        max_length=150, verbose_name="Client (Ex: Ericsson, Huawei)"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du Projet"),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin estimée"
                    ),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coordinated_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coordonnateur Assigné",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Le pays détermine l'isolation des données.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.country",
                        verbose_name="Pays d'Exécution",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par (Traçabilité)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_id_client",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ID Client du Site"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nom du Site")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En Attente"),
                            ("IN_PROGRESS", "En Cours"),
                            ("COMPLETED", "Terminé"),
                            ("CANCELED", "Annulé"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut du Site",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sites_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par (Traçabilité)",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="projects.project",
                        verbose_name="Projet Parent",
                    ),
                ),
                (
                    "team_lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="led_sites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Team Lead Assigné",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
                "ordering": ["site_id_client"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description de la Tâche"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TO_DO", "À Faire"),
                            ("IN_PROGRESS", "En Cours"),
                            ("QC_PENDING", "QC En Attente"),
                            ("APPROVED", "Approuvée"),
                            ("REJECTED", "Rejetée"),
                        ],
                        default="TO_DO",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_paid_relevant",
                    models.BooleanField(
                        default=False,
                        help_text="Cocher si la complétion de cette tâche déclenche un paiement au terrain.",
                        verbose_name="Pertinent pour la paie",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Date Limite")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigné à",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par (Traçabilité)",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.site",
                        verbose_name="Site d'Exécution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tâche",
                "verbose_name_plural": "Tâches",
                "ordering": ["due_date"],
            },
        ),
    ]
