# Generated by Django 5.2.6 on 2025-09-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["due_date", "site__project__name", "description"],
                "verbose_name": "Tâche",
                "verbose_name_plural": "Tâches",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="expected_duration_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Durée Attendue (Heures)",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="progress_percentage",
            field=models.IntegerField(default=0, verbose_name="Progression (%)"),
        ),
    ]
