# Generated by Django 5.2.6 on 2025-09-30 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_task_options_task_expected_duration_hours_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="antenna_plan",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ANTENNA PLAN (Ref/Doc)"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="atp_done",
            field=models.BooleanField(
                default=False, verbose_name="Acceptation Client (ATP) Validée"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="bb_plan",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="BB PLAN (Ref/Doc)"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="enclosure_plan",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ENCLOSURE PLAN (Ref/Doc)"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="pre_pat_result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FTR", "First Time Right (FTR)"),
                    ("NFTR", "Not First Time Right (NFTR)"),
                ],
                max_length=4,
                null=True,
                verbose_name="Résultat PRE-PAT (FTR/NFTR)",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="projet_scope",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="PROJET SCOPE (Ref/Doc)"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="radio_plan",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="RADIO PLAN (Ref/Doc)"
            ),
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_inspection",
                    models.CharField(
                        choices=[
                            ("PRE_PAT", "Pré-Validation Interne (PRE-PAT)"),
                            ("ATP", "Acceptation Client (ATP)"),
                        ],
                        max_length=10,
                        verbose_name="Type d'Inspection",
                    ),
                ),
                (
                    "resultat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FTR", "First Time Right (FTR)"),
                            ("NFTR", "Not First Time Right (NFTR)"),
                        ],
                        max_length=4,
                        null=True,
                        verbose_name="Résultat",
                    ),
                ),
                (
                    "date_inspection",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de l'Inspection"
                    ),
                ),
                (
                    "rapport_photos_url",
                    models.URLField(blank=True, verbose_name="Lien du Rapport/Photos"),
                ),
                ("commentaires", models.TextField(blank=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_inspections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Inspecteur",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="projects.site",
                        verbose_name="Site Inspecté",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection/Validation",
                "verbose_name_plural": "Inspections/Validations",
                "unique_together": {("site", "type_inspection")},
            },
        ),
    ]
