# Generated by Django 5.2.6 on 2025-09-30 22:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_site_antenna_plan_site_atp_done_site_bb_plan_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inspection",
            options={
                "ordering": ["-date_inspection"],
                "verbose_name": "Inspection",
                "verbose_name_plural": "Inspections",
            },
        ),
        migrations.AlterUniqueTogether(
            name="inspection",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="inspection",
            name="resultat_inspection",
            field=models.CharField(
                choices=[
                    ("FTR", "FTR (First Time Right)"),
                    ("NFTR", "NFTR (Not First Time Right)"),
                ],
                default="FTR",
                max_length=5,
                verbose_name="Résultat",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inspection",
            name="commentaires",
            field=models.TextField(
                blank=True, verbose_name="Commentaires de l'Inspecteur"
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="date_inspection",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Date de l'Inspection"
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="inspector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inspections_performed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Inspecteur",
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="rapport_photos_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Lien Rapport Photos/Drive",
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="type_inspection",
            field=models.CharField(
                choices=[
                    ("PRE_PAT", "PRE-PAT (Pré-Validation)"),
                    ("ATP", "ATP (Acceptance Finale Client)"),
                ],
                max_length=10,
                verbose_name="Type d'Inspection",
            ),
        ),
        migrations.RemoveField(
            model_name="inspection",
            name="resultat",
        ),
    ]
