# Generated by Django 5.2.6 on 2025-10-09 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_site_last_inspection_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Date de début"
            ),
        ),
    ]
