# Generated by Django 5.2.6 on 2025-10-10 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_project_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="progress_percentage",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Pourcentage de Progrès du Site",
            ),
        ),
    ]
