# Generated by Django 5.2.6 on 2025-10-10 10:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_site_progress_percentage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["due_date", "status"],
                "verbose_name": "Tâche d'Exécution",
                "verbose_name_plural": "Tâches d'Exécution",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="progress_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Pourcentage de Progrès du Site",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Complétée par",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="completed_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de Complétion"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="progress_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Progression Site (%)",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="expected_duration_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Durée Estimée (heures)",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_paid_relevant",
            field=models.BooleanField(
                default=False, verbose_name="Tâche Pertinente pour la Paie"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="progress_percentage",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Progression Tâche (%)",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.site",
                verbose_name="Site Parent",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("TO_DO", "À Faire"),
                    ("IN_PROGRESS", "En Cours"),
                    ("QC_PENDING", "Contrôle Qualité (QC)"),
                    ("COMPLETED", "Terminée"),
                    ("BLOCKED", "Bloquée"),
                ],
                default="TO_DO",
                max_length=15,
                verbose_name="Statut de la Tâche",
            ),
        ),
    ]
