# Generated by Django 5.2.6 on 2025-10-10 12:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_task_options_project_progress_percentage_and_more"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AntennaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la référence"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Type d'Antenne",
                "verbose_name_plural": "Types d'Antennes",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la référence"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Batch de Site",
                "verbose_name_plural": "Batches de Sites",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BBMLType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la référence"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "BB / ML",
                "verbose_name_plural": "BB / ML",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnclosureType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la référence"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Type d'Enclosure (Boîtier)",
                "verbose_name_plural": "Types d'Enclosures (Boîtiers)",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RadioType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la référence"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Modèle de Radio",
                "verbose_name_plural": "Modèles de Radio",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SitePhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la référence"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Phase de Site",
                "verbose_name_plural": "Phases de Sites",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Projet", "verbose_name_plural": "Projets"},
        ),
        migrations.AlterModelOptions(
            name="site",
            options={
                "ordering": ["project", "site_id_client"],
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["due_date", "site__site_id_client"],
                "verbose_name": "Tâche",
                "verbose_name_plural": "Tâches",
            },
        ),
        migrations.RemoveField(
            model_name="site",
            name="antenna_plan",
        ),
        migrations.RemoveField(
            model_name="site",
            name="atp_done",
        ),
        migrations.RemoveField(
            model_name="site",
            name="bb_plan",
        ),
        migrations.RemoveField(
            model_name="site",
            name="enclosure_plan",
        ),
        migrations.RemoveField(
            model_name="site",
            name="last_inspection_result",
        ),
        migrations.RemoveField(
            model_name="site",
            name="pre_pat_result",
        ),
        migrations.RemoveField(
            model_name="site",
            name="projet_scope",
        ),
        migrations.RemoveField(
            model_name="site",
            name="radio_plan",
        ),
        migrations.RemoveField(
            model_name="task",
            name="completed_by",
        ),
        migrations.RemoveField(
            model_name="task",
            name="completed_date",
        ),
        migrations.AddField(
            model_name="site",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Commentaire du Site"),
        ),
        migrations.AddField(
            model_name="site",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Localisation"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="project_scope",
            field=models.TextField(blank=True, verbose_name="Portée du Projet"),
        ),
        migrations.AddField(
            model_name="site",
            name="site_area",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Site Area"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("INSTALLATION", "Installation"),
                    ("INTEGRATION", "Intégration"),
                    ("SRS", "SRS"),
                    ("IMK", "IMK"),
                    ("EHS", "EHS"),
                    ("QA", "QA"),
                    ("ATP", "ATP"),
                    ("OTHER", "Autre"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="Type de Tâche",
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="resultat_inspection",
            field=models.CharField(
                choices=[
                    ("FTR", "First Time Right (FTR)"),
                    ("NFTR", "Not First Time Right (NFTR)"),
                ],
                max_length=5,
                verbose_name="Résultat",
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="type_inspection",
            field=models.CharField(
                choices=[
                    ("PRE_PAT", "Pré-Validation Interne (PRE-PAT)"),
                    ("ATP", "Acceptation Client (ATP)"),
                ],
                max_length=10,
                verbose_name="Type d'Inspection",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="coordinator",
            field=models.ForeignKey(
                help_text="L'utilisateur désigné pour gérer le projet (Project Coordinator/CM).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coordinated_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Coordonnateur du Projet",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de Fin Estimée"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="progress_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Progression Globale (%)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(verbose_name="Date de Démarrage"),
        ),
        migrations.AlterField(
            model_name="site",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nom du Site"),
        ),
        migrations.AlterField(
            model_name="site",
            name="progress_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Progression (%)",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="site_id_client",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="ID du Site Client"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="status",
            field=models.CharField(
                default="TO_DO", max_length=20, verbose_name="Statut Général du Site"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="team_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_sites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Team Lead Assigné",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="expected_duration_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Durée Estimée (h)",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_paid_relevant",
            field=models.BooleanField(
                default=False, verbose_name="Pertinent pour la Paie"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="progress_percentage",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Progression (%)",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.site",
                verbose_name="Site Associé",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("TO_DO", "À Faire"),
                    ("IN_PROGRESS", "En Cours"),
                    ("QC_PENDING", "Contrôle Qualité (QC)"),
                    ("COMPLETED", "Terminée"),
                    ("BLOCKED", "Bloquée"),
                ],
                default="TO_DO",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("country", "name")},
        ),
        migrations.AddField(
            model_name="site",
            name="antenna_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.antennatype",
                verbose_name="Type d'Antenne",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.batch",
                verbose_name="Batch",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="bb_ml",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.bbmltype",
                verbose_name="BB / ML",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="enclosure_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.enclosuretype",
                verbose_name="Type d'Enclosure",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.sitephase",
                verbose_name="Phase",
            ),
        ),
        migrations.CreateModel(
            name="SiteRadioConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "radio_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.radiotype",
                        verbose_name="Modèle de Radio",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radio_configurations",
                        to="projects.site",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Radio",
                "verbose_name_plural": "Configurations Radio",
                "unique_together": {("site", "radio_type")},
            },
        ),
    ]
