# Generated by Django 5.2.6 on 2025-10-10 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_task_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nom du Type d'Installation",
                    ),
                ),
                (
                    "is_transmission_link",
                    models.BooleanField(
                        default=False,
                        verbose_name="Nécessite deux sites (Liaison Transmission)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Est Actif"),
                ),
            ],
            options={
                "verbose_name": "Type d'Installation (RAN/Transmission)",
                "verbose_name_plural": "Types d'Installation",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SiteType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du Type de Site"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Est Actif"),
                ),
            ],
            options={
                "verbose_name": "Type de Site (Rooftop/Greenfield)",
                "verbose_name_plural": "Types de Sites",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="site",
            name="installation_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sites",
                to="projects.installationtype",
                verbose_name="Type d'Installation",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="site_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sites",
                to="projects.sitetype",
                verbose_name="Type de Site",
            ),
        ),
        migrations.CreateModel(
            name="TransmissionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ID de la Liaison"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site_a",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transmission_link_a",
                        to="projects.site",
                        verbose_name="Site A",
                    ),
                ),
                (
                    "site_b",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transmission_link_b",
                        to="projects.site",
                        verbose_name="Site B",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liaison Transmission",
                "verbose_name_plural": "Liaisons Transmission",
            },
        ),
    ]
