# Generated by Django 5.2.6 on 2025-10-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0012_projecttype_project_is_active_project_is_completed_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="installationtype",
            name="is_transmission_link",
        ),
    ]
