# Generated by Django 5.2.6 on 2025-10-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_remove_installationtype_is_transmission_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="is_transmission_a_site",
            field=models.BooleanField(
                default=False, verbose_name="Site A de Transmission"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="is_transmission_b_site",
            field=models.BooleanField(
                default=False, verbose_name="Site B de Transmission"
            ),
        ),
    ]
