# Generated by Django 5.2.6 on 2025-10-11 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_site_is_transmission_a_site_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nom du type de tâche"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Code unique"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PREPARATION", "Préparation"),
                            ("INSTALLATION", "Installation"),
                            ("TESTING", "Tests et Validation"),
                            ("DOCUMENTATION", "Documentation"),
                            ("SAFETY", "Sécurité"),
                            ("CLOSURE", "Clôture"),
                        ],
                        default="INSTALLATION",
                        max_length=50,
                    ),
                ),
                (
                    "expected_duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Durée estimée (heures)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
            ],
            options={
                "verbose_name": "Type de Tâche",
                "verbose_name_plural": "Types de Tâches",
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.tasktype",
                verbose_name="Type de tâche",
            ),
        ),
    ]
