# Generated by Django 5.2.6 on 2025-10-11 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_tasktype_alter_task_task_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskResultType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nom du résultat"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_success",
                    models.BooleanField(default=True, verbose_name="Est un succès"),
                ),
            ],
            options={
                "verbose_name": "Type de Résultat",
                "verbose_name_plural": "Types de Résultats",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="completion_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de complétion"
            ),
        ),
        migrations.AddField(
            model_name="tasktype",
            name="photo_instructions",
            field=models.TextField(
                blank=True, verbose_name="Instructions pour les photos"
            ),
        ),
        migrations.AddField(
            model_name="tasktype",
            name="requires_photos",
            field=models.BooleanField(
                default=False, verbose_name="Requiert des photos"
            ),
        ),
        migrations.CreateModel(
            name="TaskPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="task_photos/%Y/%m/%d/", verbose_name="Photo"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Légende"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_images",
                        to="projects.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo de Tâche",
                "verbose_name_plural": "Photos de Tâches",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="photos",
            field=models.ManyToManyField(
                blank=True,
                related_name="tasks_with_this_photo",
                to="projects.taskphoto",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="result_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.taskresulttype",
                verbose_name="Résultat de la tâche",
            ),
        ),
        migrations.AddField(
            model_name="tasktype",
            name="allowed_result_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Types de résultats que l'utilisateur peut sélectionner",
                to="projects.taskresulttype",
                verbose_name="Types de résultats autorisés",
            ),
        ),
    ]
