# Generated by Django 5.2.6 on 2025-10-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_taskresulttype_task_completion_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="photos",
        ),
    ]
