# Generated by Django 5.2.6 on 2025-10-18 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0018_site_last_inspection_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.departement', verbose_name='Département'),
        ),
    ]
