# Generated by Django 5.2.6 on 2025-10-24 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_client_remove_project_client_name_project_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date de Fin"),
        ),
        migrations.AddField(
            model_name="site",
            name="start_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Date de Démarrage"
            ),
        ),
    ]
