# Generated by Django 5.2.6 on 2025-10-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_site_end_date_site_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="ticket_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Numéro de Ticket"
            ),
        ),
    ]
