# Generated by Django 5.2.6 on 2025-10-27 06:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_task_ticket_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget_alloue",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Budget Alloué",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="statut",
            field=models.CharField(
                choices=[
                    ("PREPARATION", "En préparation"),
                    ("IN_PROGRESS", "En cours"),
                    ("COMPLETED", "Terminé"),
                    ("INVOICED", "Facturé"),
                    ("PAID", "Payé"),
                ],
                default="PREPARATION",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
