# Generated by Django 5.2.6 on 2025-10-27 23:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_workcompletionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='po_recu',
            field=models.BooleanField(default=False, verbose_name='PO Reçu'),
        ),
        migrations.AddField(
            model_name='site',
            name='prix_facturation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Prix de Facturation'),
        ),
    ]
