# Generated by Django 5.2.6 on 2025-10-29 11:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_site_po_recu_site_prix_facturation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UninstallationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "storage_location",
                    models.CharField(
                        help_text="Entrepôt, magasin, etc.",
                        max_length=255,
                        verbose_name="Lieu de stockage du matériel",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date du rapport"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uninstallation_reports_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uninstallation_report",
                        to="projects.task",
                        verbose_name="Tâche de désinstallation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport de Désinstallation",
                "verbose_name_plural": "Rapports de Désinstallation",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="UninstalledEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de l'équipement"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Numéro de série"
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Code produit"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Commentaire")),
                (
                    "uninstallation_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uninstalled_equipments",
                        to="projects.uninstallationreport",
                        verbose_name="Rapport de désinstallation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Équipement Désinstallé",
                "verbose_name_plural": "Équipements Désinstallés",
            },
        ),
    ]
