# Generated by Django 5.2.6 on 2025-10-29 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_create_desinstallation_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="uninstalledequipment",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Quantité",
            ),
        ),
    ]
