# Generated by Django 5.2.6 on 2025-10-29 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_uninstalledequipment_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="installation_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sites",
                to="projects.installationtype",
                verbose_name="Type d'Installation",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="site_id_client",
            field=models.CharField(max_length=50, verbose_name="ID du Site Client"),
        ),
    ]
