# Generated by Django 5.2.6 on 2025-10-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_alter_site_installation_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transmissionlink",
            name="link_id",
            field=models.CharField(max_length=50, verbose_name="ID de la Liaison"),
        ),
    ]
