# Generated by Django 5.2.6 on 2025-10-29 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0030_alter_transmissionlink_link_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transmissionlink",
            name="site_a",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transmission_link_a",
                to="projects.site",
                verbose_name="Site A",
            ),
        ),
        migrations.AlterField(
            model_name="transmissionlink",
            name="site_b",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transmission_link_b",
                to="projects.site",
                verbose_name="Site B",
            ),
        ),
    ]
