# Generated by Django 5.2.6 on 2025-10-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_alter_transmissionlink_site_a_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktype",
            name="points_value",
            field=models.IntegerField(default=1, verbose_name="Valeur en points"),
        ),
    ]
