# Generated by Django 5.2.6 on 2025-10-27 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0024_workcompletionrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vehicule', models.CharField(max_length=200, verbose_name='Nom du véhicule')),
                ('type', models.CharField(choices=[('PROPRIETAIRE', 'Propriétaire'), ('LOUE', 'Loué')], max_length=20, verbose_name='Type')),
                ('statut', models.CharField(choices=[('OPERATIONNEL', 'Opérationnel'), ('EN_REPARATION', 'En réparation'), ('HORS_SERVICE', 'Hors service')], default='OPERATIONNEL', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
            },
        ),
        migrations.CreateModel(
            name='MissionLogistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif')),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_conduites', to=settings.AUTH_USER_MODEL, verbose_name='Conducteur')),
                ('site_concerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_logistiques', to='projects.site', verbose_name='Site concerné')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='logistique.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Mission Logistique',
                'verbose_name_plural': 'Missions Logistiques',
            },
        ),
    ]
