# Generated by Django 5.2.6 on 2025-11-07 11:44

import datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistique", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="missionlogistique",
            name="end_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date de fin"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="missionlogistique",
            name="start_date",
            field=models.DateField(
                default=datetime.date(2025, 1, 1), verbose_name="Date de début"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="missionlogistique",
            name="team_members",
            field=models.ManyToManyField(
                related_name="missions_equipe",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Membres de l'équipe",
            ),
        ),
    ]
