# Generated by Django 5.2.6 on 2025-10-18 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du Département')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='users.country', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['country', 'name'],
                'unique_together': {('name', 'country')},
            },
        ),
    ]
