# Generated by Django 5.2.6 on 2025-09-27 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date de la Dépense")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant (€ / XOF etc.)",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Approuvée ?"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Clé d'isolation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.country",
                        verbose_name="Pays",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Saisie par",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.site",
                        verbose_name="Site/Localisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dépense Quotidienne",
                "verbose_name_plural": "Dépenses Quotidiennes",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="WorkCompletionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant payé pour cette tâche",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        auto_now_add=True,
                        verbose_name="Date de l'enregistrement de paie",
                    ),
                ),
                (
                    "is_paid_out",
                    models.BooleanField(
                        default=False, verbose_name="Paiement effectué ?"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé concerné (celui qui a fait la tâche)",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        help_text="La tâche doit être marquée 'is_paid_relevant' et 'APPROVED'.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.task",
                        verbose_name="Tâche liée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche de Paie Terrain",
                "verbose_name_plural": "Fiches de Paie Terrain",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant de base (par jour/mois)",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.country",
                        verbose_name="Pays",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.role",
                        verbose_name="Rôle concerné",
                    ),
                ),
            ],
            options={
                "verbose_name": "Structure Salariale",
                "verbose_name_plural": "Structures Salariales",
                "unique_together": {("country", "role")},
            },
        ),
    ]
