# Generated by Django 5.2.6 on 2025-09-27 11:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. AJOUTER TOUS LES NOUVEAUX CHAMPS EN PREMIER
        migrations.AddField(
            model_name="workcompletionrecord",
            name="completion_percentage",
            field=models.DecimalField(default=0, max_digits=5, decimal_places=2),
        ),
        migrations.AddField(
            model_name="workcompletionrecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        # Assurez-vous que tous les AddField sont ici (date, user, created_by, etc.)
        migrations.AddField(
            model_name="workcompletionrecord",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workcompletionrecord",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        # 2. ENSUITE, SUPPRIMER LES ANCIENS CHAMPS
        migrations.RemoveField(
            model_name="workcompletionrecord",
            name="employee",
        ),
        # ... RemoveField pour paid_amount, payment_date, etc.
        # 3. ENFIN, LES OPÉRATIONS QUI MODIFIENT LES CONTRAINTES ou METAS (Unique Together, Options, Alter Field)
        migrations.AlterModelOptions(
            name="workcompletionrecord",
            options={"ordering": ["-date"]},  # ou autre
        ),
        migrations.AlterUniqueTogether(
            name="workcompletionrecord",
            unique_together={
                ("user", "task", "date")
            },  # Doit être après l'ajout de 'date' et 'user'
        ),
        # 4. AlterField à la fin si nécessaire (comme celui sur 'task')
        migrations.AlterField(
            model_name="workcompletionrecord",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="completion_records",
                to="projects.task",
            ),
        ),
    ]
