# Generated by Django 5.2.6 on 2025-09-27 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_workcompletionrecord_options_and_more"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workcompletionrecord",
            options={
                "verbose_name": "Enregistrement d'Achèvement de Travail",
                "verbose_name_plural": "Enregistrements d'Achèvement de Travail",
            },
        ),
        migrations.AlterUniqueTogether(
            name="workcompletionrecord",
            unique_together={("task", "date", "user")},
        ),
        migrations.AddField(
            model_name="workcompletionrecord",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_records_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workcompletionrecord",
            name="duration_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Durée (Heures)",
            ),
        ),
        migrations.AlterField(
            model_name="workcompletionrecord",
            name="completion_percentage",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Achèvement de la Tâche (%)"
            ),
        ),
        migrations.AlterField(
            model_name="workcompletionrecord",
            name="date",
            field=models.DateField(verbose_name="Date de travail"),
        ),
        migrations.AlterField(
            model_name="workcompletionrecord",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.task",
                verbose_name="Tâche Complétée",
            ),
        ),
        migrations.AlterField(
            model_name="workcompletionrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Employé (Ouvrier)",
            ),
        ),
        migrations.RemoveField(
            model_name="workcompletionrecord",
            name="is_paid_out",
        ),
        migrations.RemoveField(
            model_name="workcompletionrecord",
            name="paid_amount",
        ),
        migrations.RemoveField(
            model_name="workcompletionrecord",
            name="payment_date",
        ),
    ]
