# Generated by Django 5.2.6 on 2025-09-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_workcompletionrecord_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workcompletionrecord",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Coût de l'Enregistrement",
            ),
        ),
        migrations.AddField(
            model_name="workcompletionrecord",
            name="hourly_rate_used",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Taux Horaire Utilisé",
            ),
        ),
    ]
