# Generated by Django 5.2.6 on 2025-10-08 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_workcompletionrecord_cost_and_more"),
        ("projects", "0005_site_last_inspection_result"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- 1. AJOUTER le nouveau champ 'employee' en premier ---
        migrations.AddField(
            model_name="workcompletionrecord",
            name="employee",
            # IMPORTANT: Le 'preserve_default=False' indique que le 'default=1' sera
            # utilisé pour peupler les lignes existantes.
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Employé (Ouvrier)",
            ),
            preserve_default=False,
        ),
        # --- 2. Modifier les options du modèle (sans dépendance aux champs) ---
        migrations.AlterModelOptions(
            name="workcompletionrecord",
            options={
                "ordering": ["-date", "task__id"],
                "verbose_name": "Enregistrement d'Achèvement de Travail",
                "verbose_name_plural": "Enregistrements d'Achèvement de Travail",
            },
        ),
        # --- 3. Appliquer la contrainte unique (maintenant que 'employee' existe) ---
        migrations.AlterUniqueTogether(
            name="workcompletionrecord",
            unique_together={("task", "date", "employee")},
        ),
        # --- 4. Ajouter les autres champs non problématiques ---
        migrations.AddField(
            model_name="workcompletionrecord",
            name="is_paid_out",
            field=models.BooleanField(
                default=False, verbose_name="Paiement effectué ?"
            ),
        ),
        # --- 5. Modifications de champs existants (non problématiques) ---
        migrations.AlterField(
            model_name="workcompletionrecord",
            name="hourly_rate_used",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Taux Horaire Utilisé (pour historique)",
            ),
        ),
        migrations.AlterField(
            model_name="workcompletionrecord",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.task",
                verbose_name="Tâche Complétée",
            ),
        ),
        # --- 6. Supprimer l'ancien champ 'user' en dernier ---
        migrations.RemoveField(
            model_name="workcompletionrecord",
            name="user",
        ),
    ]
