# Generated by Django 5.2.6 on 2025-10-27 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_alter_workcompletionrecord_options_and_more"),
        ("projects", "0023_project_budget_alloue_project_statut"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="salarystructure",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="country",
        ),
        migrations.RemoveField(
            model_name="salarystructure",
            name="role",
        ),
        migrations.AlterUniqueTogether(
            name="workcompletionrecord",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="workcompletionrecord",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="workcompletionrecord",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="workcompletionrecord",
            name="task",
        ),
        migrations.CreateModel(
            name="Depense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date de la dépense")),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("SALAIRE", "Salaire"),
                            ("TRANSPORT", "Transport"),
                            ("MATERIEL", "Matériel"),
                            ("LOYER", "Loyer"),
                            ("SOUS_TRAITANT", "Sous-traitant"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "recu_scan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="recus_depenses/",
                        verbose_name="Reçu scanné",
                    ),
                ),
                (
                    "employe_declarant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depenses_declarees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé déclarant",
                    ),
                ),
                (
                    "projet_associe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depenses",
                        to="projects.project",
                        verbose_name="Projet associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dépense",
                "verbose_name_plural": "Dépenses",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Revenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(verbose_name="Date de réception du paiement"),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant reçu"
                    ),
                ),
                (
                    "projet_facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenus",
                        to="projects.project",
                        verbose_name="Projet facturé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revenu",
                "verbose_name_plural": "Revenus",
                "ordering": ["-date"],
            },
        ),
        migrations.DeleteModel(
            name="DailyExpense",
        ),
        migrations.DeleteModel(
            name="SalaryStructure",
        ),
        migrations.DeleteModel(
            name="WorkCompletionRecord",
        ),
    ]
