# Generated by Django 5.2.6 on 2025-10-27 11:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_alter_salarystructure_unique_together_and_more"),
        ("users", "0002_customuser_salaire_mensuel_base_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Montant de base (mensuel)",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.country",
                        verbose_name="Pays/Filiale",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.role",
                        verbose_name="Rôle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Structure Salariale",
                "verbose_name_plural": "Structures Salariales",
                "unique_together": {("country", "role")},
            },
        ),
    ]
