# Generated by Django 5.2.6 on 2025-10-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_salarystructure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depense",
            name="recu_scan",
            field=models.FileField(
                default=1, upload_to="recus_depenses/", verbose_name="Reçu scanné"
            ),
            preserve_default=False,
        ),
    ]
