# Generated by Django 5.2.6 on 2025-10-27 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_depense_recu_scan'),
        ('inventaire', '0001_initial'),
        ('projects', '0024_workcompletionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObligationFiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_impot', models.CharField(max_length=100, verbose_name="Type d'impôt")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('montant_a_payer', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant à payer')),
                ('montant_paye', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant payé')),
                ('statut', models.CharField(choices=[('A_PAYER', 'À Payer'), ('PAYE', 'Payé'), ('EN_RETARD', 'En Retard')], default='A_PAYER', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Obligation Fiscale',
                'verbose_name_plural': 'Obligations Fiscales',
                'ordering': ['date_echeance'],
            },
        ),
        migrations.AddField(
            model_name='depense',
            name='equipement_concerne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='inventaire.equipement', verbose_name='Équipement concerné'),
        ),
        migrations.AddField(
            model_name='depense',
            name='site_concerne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='projects.site', verbose_name='Site concerné'),
        ),
    ]
