# Generated by Django 5.2.6 on 2025-10-27 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_obligationfiscale_depense_equipement_concerne_and_more'),
        ('logistique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='vehicule_concerne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='logistique.vehicule', verbose_name='Véhicule concerné'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='categorie',
            field=models.CharField(choices=[('LOYER', 'Loyer'), ('ELECTRICITE', 'Electricité'), ('EAU', 'Eau'), ('CARBURANT', 'Carburant'), ('SALAIRE', 'Salaire'), ('IMPOTS', 'Impôts'), ('ACHAT_MATERIEL', 'Achat Matériel'), ('REPARATION_VEHICULE', 'Réparation Véhicule'), ('REPARATION_EQUIPEMENT', 'Réparation Équipement'), ('CERTIFICATION', 'Certification'), ('TRANSPORT', 'Transport'), ('SOUS_TRAITANT', 'Sous-traitant'), ('AUTRE', 'Autre')], max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='obligationfiscale',
            name='depense_associee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligation_fiscale', to='finance.depense', verbose_name='Dépense associée'),
        ),
    ]
