# Generated by Django 5.2.6 on 2025-10-27 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0009_obligationfiscale_depense_equipement_concerne_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_certification', models.CharField(max_length=200, verbose_name='Nom de la certification')),
                ('date_expiration', models.DateField(verbose_name="Date d'expiration")),
                ('depense_associee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='finance.depense', verbose_name='Dépense associée')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
            },
        ),
        migrations.CreateModel(
            name='PaiementSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(verbose_name='Mois')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé')),
                ('depense_associee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement_salaire', to='finance.depense', verbose_name='Dépense associée')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_salaires', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Paiement de Salaire',
                'verbose_name_plural': 'Paiements de Salaires',
                'unique_together': {('employe', 'mois', 'annee')},
            },
        ),
    ]
