# Generated by Django 5.2.6 on 2025-10-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="fichier_certificat",
            field=models.FileField(
                default=1,
                upload_to="certifications/",
                verbose_name="Fichier du certificat",
            ),
            preserve_default=False,
        ),
    ]
