# Generated by Django 5.2.6 on 2025-11-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0003_contract"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(max_length=50, verbose_name="Type de document"),
                ),
                ("year", models.IntegerField(verbose_name="Année")),
                (
                    "last_number",
                    models.IntegerField(
                        default=0, verbose_name="Dernier numéro utilisé"
                    ),
                ),
            ],
            options={
                "verbose_name": "Compteur de document",
                "verbose_name_plural": "Compteurs de documents",
                "unique_together": {("document_type", "year")},
            },
        ),
    ]
