# Generated by Django 5.2.6 on 2025-10-27 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_equipement', models.CharField(max_length=200, verbose_name="Nom de l'équipement")),
                ('numero_serie', models.CharField(max_length=200, unique=True, verbose_name='Numéro de série')),
                ('cout_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Coût d'achat")),
                ('date_prochaine_inspection', models.DateField(verbose_name='Date de prochaine inspection')),
                ('statut', models.CharField(choices=[('EN_STOCK', 'En stock'), ('ALLOUE', 'Alloué'), ('EN_MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], default='EN_STOCK', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
            },
        ),
        migrations.CreateModel(
            name='AllocationEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignation', models.DateField(verbose_name="Date d'assignation")),
                ('employe_assigne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Employé assigné')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventaire.equipement', verbose_name='Équipement')),
            ],
            options={
                'verbose_name': "Allocation d'équipement",
                'verbose_name_plural': "Allocations d'équipement",
            },
        ),
    ]
