# Generated by Django 5.2.6 on 2025-11-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("permission", "Permission"),
                    ("leave", "Congé"),
                    ("certification", "Demande de certification"),
                    ("attestation", "Demande d'attestation"),
                ],
                max_length=20,
            ),
        ),
    ]
